name: "multi_cloud_data_mesh"
version: "1.0.0"
config-version: 2
profile: "multi_cloud_data_mesh"

models:
  multi_cloud_data_mesh:
    +materialized: view
    staging:
      +schema: staging
      +post-hook:
        - "{% if env_var('APPLY_POLICY_TAGS', 'false') == 'true' %} {{ apply_policy_tags_from_map() }} {% endif %}"
    marts:
      +schema: marts
      +post-hook:
        - "{% if env_var('APPLY_POLICY_TAGS', 'false') == 'true' %} {{ apply_policy_tags_from_map() }} {% endif %}"

seeds:
  +quote_columns: false

tests:
  +store_failures: true
