repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args: ["--args=--enable-rule=terraform_documented_outputs"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-d", "{extends: default, rules: {line-length: {max: 160}}}"]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ["dbt-bigquery"]
        files: 'dbt/.*\.sql$'
