apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-mesh-infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ruslanbaba/multi-cloud-data-mesh
    targetRevision: main
    path: infra/terraform/envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: data-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-mesh-dbt
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: data-platform
  source:
    repoURL: https://github.com/ruslanbaba/multi-cloud-data-mesh
    targetRevision: main
    path: dbt/
  destination:
    server: https://kubernetes.default.svc
    namespace: data-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
