name: dbt-ci
on:
  pull_request:
    paths:
      - 'dbt/**'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt-bigquery
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery
      - name: Authenticate to GCP via OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_DBT_SA }}
      - name: dbt deps
        working-directory: dbt
        run: dbt deps --no-write-json
      - name: dbt compile
        working-directory: dbt
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_LOCATION: US
        run: dbt compile --project-dir . --profiles-dir .
